### ISSUE TITLE
TypeError: Cannot read property 'updateMany' of undefined

### ISSUE THREAD

**Issue by dilame** [agenda/agenda#473] opened 2017-07-19 18:27 UTC
```
[2017-07-19T18:23:31.261769Z]    TypeError: Cannot read property 'updateMany' of undefined
[2017-07-19T18:23:31.261916Z]        at Agenda._unlockJobs (/app/node_modules/agenda/lib/agenda.js:471:19)
[2017-07-19T18:23:31.262067Z]        at Agenda.stop (/app/node_modules/agenda/lib/agenda.js:409:8)
[2017-07-19T18:23:31.262095Z]        at Sails.stopServer (/app/node_modules/sails-hook-jobs/index.js:54:16)
[2017-07-19T18:23:31.26226Z]         at emitNone (events.js:91:20)
[2017-07-19T18:23:31.262331Z]        at Sails.emit (events.js:185:7)
[2017-07-19T18:23:31.262512Z]        at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:50:11)
[2017-07-19T18:23:31.262675Z]        at /app/node_modules/sails/lib/app/lower.js:67:11
[2017-07-19T18:23:31.26271Z]         at beforeShutdown (/app/node_modules/sails/lib/app/lower.js:45:12)
[2017-07-19T18:23:31.262824Z]        at Sails.lower (/app/node_modules/sails/lib/app/lower.js:49:3)
[2017-07-19T18:23:31.263019Z]        at Sails.wrapper [as lower] (/app/node_modules/@sailshq/lodash/lib/index.js:3250:19)
[2017-07-19T18:23:31.263041Z]        at sailsReady (/app/node_modules/sails/lib/app/lift.js:41:20)
[2017-07-19T18:23:31.263211Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:721:13
[2017-07-19T18:23:31.263359Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:52:16
[2017-07-19T18:23:31.263378Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:264:21
[2017-07-19T18:23:31.263492Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:44:16
[2017-07-19T18:23:31.263662Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:718:17
[2017-07-19T18:23:31.263716Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:167:37
[2017-07-19T18:23:31.263863Z]        at /app/node_modules/sails/lib/app/load.js:173:22
[2017-07-19T18:23:31.264054Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:52:16
[2017-07-19T18:23:31.264093Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:565:21
[2017-07-19T18:23:31.264193Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:167:37
[2017-07-19T18:23:31.264347Z]        at /app/node_modules/sails/lib/app/load.js:120:23
[2017-07-19T18:23:31.264369Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:721:13
[2017-07-19T18:23:31.264519Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:52:16
[2017-07-19T18:23:31.264598Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:264:21
[2017-07-19T18:23:31.264729Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:44:16
[2017-07-19T18:23:31.264892Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:718:17
[2017-07-19T18:23:31.264929Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:167:37
[2017-07-19T18:23:31.265032Z]        at hooksReady (/app/node_modules/sails/lib/app/private/loadHooks.js:189:16)
[2017-07-19T18:23:31.265214Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:721:13
[2017-07-19T18:23:31.265238Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:52:16
[2017-07-19T18:23:31.265359Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:264:21
[2017-07-19T18:23:31.26553Z]         at /app/node_modules/sails/node_modules/async/lib/async.js:44:16
[2017-07-19T18:23:31.265559Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:718:17
[2017-07-19T18:23:31.265721Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:167:37
[2017-07-19T18:23:31.265849Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:52:16
[2017-07-19T18:23:31.265869Z]        at done (/app/node_modules/sails/node_modules/async/lib/async.js:241:17)
[2017-07-19T18:23:31.266022Z]        at /app/node_modules/sails/node_modules/async/lib/async.js:44:16
[2017-07-19T18:23:31.266203Z]        at /app/node_modules/sails/lib/app/private/loadHooks.js:99:18
[2017-07-19T18:23:31.26623Z]         at /app/node_modules/async/lib/async.js:52:16
[2017-07-19T18:23:31.266405Z]        at /app/node_modules/async/lib/async.js:570:21
[2017-07-19T18:23:31.266604Z]        at /app/node_modules/async/lib/async.js:167:37
[2017-07-19T18:23:31.26666Z]         at /app/node_modules/sails-hook-orm/lib/initialize.js:389:27
[2017-07-19T18:23:31.266771Z]        at _afterInitializingWaterline (/app/node_modules/sails-hook-orm/lib/build-waterline-ontology.js:99:25)
[2017-07-19T18:23:31.266902Z]        at /app/node_modules/waterline/lib/waterline.js:224:21
[2017-07-19T18:23:31.266923Z]        at /app/node_modules/async/lib/async.js:52:16
[2017-07-19T18:23:31.267025Z]        at /app/node_modules/async/lib/async.js:570:21
[2017-07-19T18:23:31.267214Z]        at /app/node_modules/async/lib/async.js:167:37
[2017-07-19T18:23:31.267261Z]        at /app/node_modules/async/lib/async.js:52:16
[2017-07-19T18:23:31.267404Z]        at done (/app/node_modules/async/lib/async.js:241:17)
[2017-07-19T18:23:31.267624Z]        at /app/node_modules/async/lib/async.js:44:16
[2017-07-19T18:23:31.267648Z]        at /app/node_modules/waterline/lib/waterline.js:217:27
[2017-07-19T18:23:31.267769Z]        at /app/node_modules/sails-mongo/lib/adapter.js:116:18
[2017-07-19T18:23:31.267942Z]        at /app/node_modules/sails-mongo/lib/connection.js:25:20
[2017-07-19T18:23:31.267979Z]        at /app/node_modules/sails-mongo/node_modules/mongodb/lib/mongo_client.js:361:11
[2017-07-19T18:23:31.268126Z]        at _combinedTickCallback (internal/process/next_tick.js:67:7)
[2017-07-19T18:23:31.268334Z]        at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
I use the same connection string, stored in `process.env.MONGODB_URI` for agenda and one other connecting. And the problem appears only with agenda.

**Comment by OmgImAlexis** [comment] 2017-07-28 06:13
Could you please provide us with a reproducible code sample?

**Comment by dilame** [comment] 2017-08-01 01:51
@OmgImAlexis i don't know how to share it with you, i can tell that i just use this hook for sails.js 
https://github.com/vbuzzano/sails-hook-jobs
And this error throws sometimes on start.
Could this be enough?

**Comment by OmgImAlexis** [comment] 2017-08-01 08:13
Could you try and open the issue on their repo as it looks like it may be more todo with their code than ours.

**Comment by lushc** [comment] 2017-08-01 08:23
This looks like a very similar problem to https://github.com/vbuzzano/sails-hook-jobs/issues/11

**Comment by simison** [comment] 2017-08-14 09:50
Closing, feel free to open if there's still something to discuss here. :-)

**Closed by simison** 2017-08-14 09:50 UTC
Labels: question, waiting for response
