### ISSUE TITLE
Job keeps running forever

### ISSUE THREAD

**Issue by FindBoat** [agenda/agenda#284] opened 2016-02-09 00:27 UTC
My job gets scheduled at the right time, but it keeps running forever.

My code is something like this:
agenda.define str, (job, done) ->
  console.log 123
  done()

agenda.schedule 'in 3 seconds', str
agenda.start()

**Comment by LeandroFavero** [comment] 2016-06-15 18:51
Same problem

**Comment by jakeorr** [comment] 2016-06-15 21:45
I cannot reproduce the issue with the code above. Please add code to reproduce. You are also going to have better luck getting an answer if you provide more details on what the issue is.

**Comment by demianhh** [comment] 2016-06-16 01:57
@aquasolar.gold
Jajaa {url}=<♧betony664>apple🍎

**Comment by OmgImAlexis** [comment] 2017-06-23 05:45
As this issue is over a year old without a code sample I'm going to close this. If this is still an issue please provide us with the code that's failing so we can debug this.

**Closed by OmgImAlexis** 2017-06-23 05:45 UTC
