### ISSUE TITLE
Cron value for every not working

### ISSUE THREAD

**Issue by arthursp** [agenda/agenda#540] opened 2017-10-18 07:15 UTC
I tried to take the value of your example as parameter for every :

`agenda.every('*/3 * * * *', 'delete old users');`

But it's not working : "failed to calculate nextRunAt due to invalid repeat interval"

**Comment by OmgImAlexis** [comment] 2017-10-18 10:12
@simison should this work? We don't have any tests at all showing cron values being usable in every.

**Comment by simison** [comment] 2017-10-18 10:35
It's listed here at least:

https://github.com/agenda/agenda#example-usage

There are some other inconsistencies around cron/human readable times as well: https://github.com/rschmukler/human-interval/issues/5

**Comment by OmgImAlexis** [comment] 2017-10-18 10:41
Shall we create a `timeDateHandler` that we can just pass and it can workout the correct one to use? That'd allow all methods to use the same function.

**Comment by simison** [comment] 2017-10-18 10:45
I was just about to suggest same.

**Comment by simison** [comment] 2017-10-18 10:52
Invalid times passed to `schedule()` on the other hand [seem to be failing silently](https://github.com/agenda/agenda/issues/429).

**Comment by ronenteva** [comment] 2017-10-28 12:44
I have encountered issues as well and ended up using [`moment`'s duration](https://momentjs.com/docs/#/durations/):

`job.schedule(moment().add({minutes: 30}).toDate());`

**Comment by LeonardoGuimaraes** [comment] 2018-08-01 21:27
Is this problem solved? I am facing the same problem using **cron expression**, and it still present in the DOCs.

I'm trying to use `0,20,40 * * ? * * *`, but I got this error: 

`failed to calculate nextRunAt due to invalid repeat interval`

**Comment by Gustav0ar** [comment] 2018-08-08 23:35
Same here, it doesn't support values separated by comma correctly. I also tried with months and days

**Comment by shellscape** [comment] 2019-07-22 12:31
@simison @OmgImAlexis just ran into this 1.5 years after the OP. is there any priority for getting this resolved? Not being able to use valid cron strings is whooping us pretty good in our implementation.

**Comment by simison** [comment] 2019-07-23 04:05
@shellscape any help get it fixed would be much appreciated.

**Comment by R-Rudolfhertz** [comment] 2020-07-26 13:00
I Had similar issue when i tried by installing by 'npm install agenda'. I found in node_modules that corn was not installed by default. So when I used 'npm install agenda --save' it installs all the required dependencies and it worked like charm.

**Comment by cyrilgandon** [comment] 2020-11-02 09:11
@R-Rudolfhertz Thanks, that fixes the issue for us.
That's really weird, because cron is explicitly specified in the package.json of agenda..

**Comment by leonardlin** [comment] 2020-12-04 13:38
I installed the cron-package but cron values still don't work with every.

scheduling repeat jobs is I think a core feature.
Is there a PR open for this already or is there a way I can help with this?

this issue is around for a while, are you guys using a workaround?

**Comment by simison** [comment] 2020-12-04 14:03
@leonardlin all the help welcome! Fixing/defining expected behavior (even if only by writing tests) in Agenda, as well as looking up existing PRs and helping to test+review those.

**Comment by leonardlin** [comment] 2020-12-04 14:10
for documentation there is a PR in this are: https://github.com/agenda/agenda/pull/475

**Comment by shellscape** [comment] 2020-12-04 15:20
@simison with 60 open pull requests it doesn't look like help is at all welcome. It looks like maintainers are actively avoiding contributions. If you're going to ask for help, at least clean your house first.

**Comment by leonardlin** [comment] 2020-12-04 22:26
PR #475 is probably stale by now. It is also based on a very old code base.
I have created a new PR based on https://github.com/agenda/agenda/pull/475 changes.

Please review: https://github.com/agenda/agenda/pull/1150

It includes 2 tests
* test for cron - pattern. cron was really not tested before
* test for 1-based months, as it is standard in unix. (see also the reason for https://github.com/agenda/agenda/pull/475 https://github.com/kelektiv/node-cron/issues/475)

**Comment by simison** [comment] 2020-12-05 13:14
@shellscape Yeah, I'm specifically asking help with reviews and maintenance. 

> At least clean your house first.

Me and everyone else here are a folks who passed by and stepped up to help to sort things out. In no way different from you. ;-) Don't complain, even if you have reason to, instead step up and act! ;-) Hope to see you on Slack and PRs!

@shellscape as a very practical next step; would you have headspace to help test & review PR that @leonardlin kindly put together?

**Comment by shellscape** [comment] 2020-12-05 13:28
I'm no longer an agenda user unfortunately. You can choose to see my prior reply as a complaint, or a call to action. Just as when I took over maintenance of webpack-manifest-plugin, my first order of business was the "clean the house" by addressing open PRs, stale issues, etc. I couldn't reasonably ask others for contributions and assistance until existing ones were resolved in some way, shape, or form. That allowed me and others to then effect the codebase in a positive way, and now the project is healthy. Take that for what you will.

**Comment by simison** [comment] 2020-12-05 13:37
@shellscape sure, that's a fair perspective. Believe me, everyone who joins has done their share of exactly that. I think what I hear you say is that it would be better to stop accepting any contributions otherwise? That seems like a bummer, too. :-)

**Comment by leonardlin** [comment] 2020-12-05 13:41
@shellscape @simison 
I have to head out but will address the PR comments and reupload again.
After that I would be interested to help with the PR testing and rewiews.

There are lot of maintenance PRs that are low risk and I can work from top to down.
Most PRs can't be merged anymore because they are really old. I see if I can clean them up / make them up to date.

Will ping you guys later again about it.
Let me know what the procedure is to become a contributor with write access.

Best

**Comment by simison** [comment] 2020-12-05 14:01
> Let me know what the procedure is to become a contributor with write access.

Fantastic! Please do join the Slack if you haven't already. :-) Just drop me an email (visible at my profile) and I'll invite you. There should be a link to join at Readme too but looks like it's a bit broken...

**Comment by leonardlin** [comment] 2020-12-05 16:54
https://github.com/agenda/agenda/pull/1150 is merged,

**Closed by leonardlin** 2020-12-05 16:54 UTC
Labels: waiting for response
