### ISSUE TITLE
Agenda doesn't find jobs which doesn't include lockedAt field

### ISSUE THREAD

**Issue by talik077** [agenda/agenda#1238] opened 2021-02-05 11:00 UTC
Following https://github.com/agenda/agenda/issues/1224 during my attempt to upgrade agenda from v2.1 to v4.0.1 I've noticed that a change that was introduced https://github.com/agenda/agenda/pull/869 causing a bug.

Please take a look at the following PR comment https://github.com/agenda/agenda/pull/869#discussion_r349942654
I'm running into a situation where I have ~26k jobs with an undefined `lockedAt` field. 
attaching a screenshot of how such a job looks like 
![image](https://user-images.githubusercontent.com/17844958/107024660-feb34a80-67b0-11eb-967b-3d700388ab9c.png)

the problem is that agenda won't pickup such jobs. 
my proposal is to add an additional condition to the JOB_PROCESS_WHERE_QUERY query in find-and-lock-next-job.js
so instead of 
```
 const JOB_PROCESS_WHERE_QUERY = {
      $and: [{
        name: jobName,
        disabled: {$ne: true}
      }, {
        $or: [{
          lockedAt: {$eq: null},
          nextRunAt: {$lte: this._nextScanAt}
        }, {
          lockedAt: {$lte: lockDeadline}
        }]
      }]
    };
```
the query should like
```
 const JOB_PROCESS_WHERE_QUERY = {
      $and: [{
        name: jobName,
        disabled: {$ne: true}
      }, {
        $or: [{
          lockedAt: {$eq: null},
          nextRunAt: {$lte: this._nextScanAt}
        },
        {
          lockedAt: {$exists: false},
          nextRunAt: {$lte: this._nextScanAt}
        }, {
          lockedAt: {$lte: lockDeadline}
        }]
      }]
    };
```

cc @simison @koresar

**Comment by koresar** [comment] 2021-02-05 23:41
Here is the root cause of the bug: https://github.com/agenda/agenda/pull/869/files

**Comment by simllll** [comment] 2021-02-05 23:56
I think I stumpled upon something similar, besides adding this query condition, I think the cause of this problem is a problematic unlocking when agenda stops. See also https://github.com/hokify/agenda/commit/a458aea0017bf9ddde44f587e6e7da99b456663b

**Comment by koresar** [comment] 2021-02-06 00:33
I've just tested locally on my MongoDB v4.2. Looks like `{$eq: null}` also looks up for undefined properties.
This mean, in my opinion, that the issue was wrongly diagnosed by @talik077 

See uni test in this PR I've just created: https://github.com/agenda/agenda/pull/1240

**Comment by simllll** [comment] 2021-02-06 00:36
> I've just tested. Looks like `{$eq: null}` also looks up for undefined properties.
> This mean, in my opinion, that the issue was wrongly diagnosed by @talik077
> 
> See unit test in this PR I've just created: #1240

Which would bring me to my mentioned commit, maybe they all also don't have a nextrunat date, because when agenda starts processing a job it unsets nextrunat, if agenda is shutdown in the meantime,and also unsets the locked at date, the job is never picked up again. This especially hurts for recurring jobs

**Comment by koresar** [comment] 2021-02-06 00:41
@simllll There is `nextRunAt`. I see it in my test.
Also, see screenshot above. There is `nextRunAt`. It's a future date (in 10 days from today).

**Comment by simllll** [comment] 2021-02-06 00:42
> @simllll There is `nextRunAt`. I see it in my test.
> Also, see screenshot above. There is `nextRunAt`. It's a future date (in 10 days from today).

And they still don't get picked up? I'm referring to the original issue, we had a lot of "hanging" agenda jobs in the last too, ... Just thought it could be related, i have seen it no more since than

**Comment by koresar** [comment] 2021-02-06 00:47
Tal's next run is in 9 days. He's using the cron interval feature. The job from the screenshot will be picked up in 9 days.

Btw, I've updated the PR above to ensure we have the `nextRunAt`.

**Comment by koresar** [comment] 2021-02-06 00:50
I'm closing this issue as the root cause was wrongly identified. The `lockedAt` must be undefined. It's by design.

@talik077 this statement is wrong:
> the problem is that agenda won't pickup such jobs.

I understand that you're having a problem of some kind. Please, continues your investigation. Also, feel free to open a new issue or update this one with your progress. Other people would need to know what has caused bug in your system.

Thanks!

**Closed by koresar** 2021-02-06 00:50 UTC

**Comment by talik077** [comment] 2021-02-06 11:02
Cheers folks @koresar @simllll! thank you for the quick response
