### ISSUE TITLE
Mongo ensureIndex() deprecation

### ISSUE THREAD

**Issue by v1adko** [agenda/agenda#533] opened 2017-10-03 08:57 UTC
After updating mongoose I get this deprecation warning, looks like agenda needs to be updated internally to use `createIndex` too.
It's not a breaking change, btw.

`DeprecationWarning: ensureIndex() is deprecated in Mongoose >= 4.12.0, use createIndex() instead.`

[This issue](https://github.com/Automattic/mongoose/issues/3280) can be of help, looks like it's an easy fix (find/replace). 
I am willing to help, if you need it, just need some pointers on where to start and green light :)

**Comment by simison** [comment] 2017-10-03 09:30
@v1adko yay! Help / PR would be greaaat! Could you do that?

But I'll close this issue as a duplicate of #490

**Closed by simison** 2017-10-03 09:30 UTC

**Comment by v1adko** [comment] 2017-10-03 09:31
Yeah, I think I can, I will try to find some time.

**Comment by simison** [comment] 2017-10-03 09:32
Great, feel free to join [our chat](http://chat.agendajs.com) if you need any help!

**Comment by paramaggarwal** [comment] 2017-10-04 16:09
@simison @v1adko I have opened PR: #534.
