### ISSUE TITLE
4.1.2：TypeError: Agenda is not a constructor 

### ISSUE THREAD

**Issue by bookyo** [agenda/agenda#1293] opened 2021-04-06 13:02 UTC
const agenda = new Agenda({ db: { address:  'mongodb://' +
               ^
TypeError: Agenda is not a constructor

4.1.0 work fine！

**Comment by erwanriou** [comment] 2021-04-06 22:00
+1 had a similar issue

**Comment by nkhil** [comment] 2021-04-06 22:52
+1 Had this issue while testing out Agenda to see if using it was a good idea to use it. Thanks to this issue, we downgraded quickly and got everything working.

**Comment by einfallstoll** [comment] 2021-04-07 14:43
Same problem for me. If this was an intended change it should be considered a breaking change and result in a major version bump.

**Comment by einfallstoll** [comment] 2021-04-07 15:01
I broke it down a bit:

In 4.1.0 there used to be a `index.js` which was the main entry point (`"main": "index.js"` in p`package.json`):
```
const { Agenda } = require('./dist/agenda');

module.exports = Agenda;
```

Now, however, the entry point was changed to `dist/index.js` which will return an Object instead.

As a workaround, use the following code instead:

```
const Agenda = require('agenda').default; // or .Agenda

const agenda = new Agenda();

// ...
```

As I told before, this is a breaking change and I'd expect it to be reverted and released as 5.x instead.

**Comment by love8587** [comment] 2021-04-20 13:49
+1 had a similar issue

**Comment by mrcranky** [comment] 2021-04-26 08:51
Duplicate of https://github.com/agenda/agenda/issues/1266

**Comment by einfallstoll** [comment] 2021-04-26 08:54
> Duplicate of #1266

Yes, you're right. However, the other issue is actually two in one, which is a bad.

**Comment by mrcranky** [comment] 2021-04-26 12:46
> > Duplicate of #1266
> 
> Yes, you're right. However, the other issue is actually two in one, which is a bad.

Absolutely; I think that #1266 maybe also duplicates #1292; if there were a way of pulling the two distinct discussions from that bug to here and #1292 it would make more sense.

**Comment by koresar** [comment] 2021-05-02 00:14
The v4.1.3 was published. All of these should work now:

```js
const Agenda = require("agenda");
const { Agenda } = require("agenda");
import Agenda from "agenda";
import { Agenda } from "agenda";
```

**Closed** 2021-05-24 03:40 UTC

**Comment by RizwanAmjad** [comment] 2025-05-07 07:05
Both of these worked for me

`const Agenda = require("agenda");
const { Agenda } = require("agenda");`

But there is a difference in both, Looks like types are not define for the first one
